UI_CAPABILITIES = {
    "data-table",
    "command-palette",
    "auth-ui",
    "settings",
    "dashboard",
    "forms",
    "file-upload",
    "charts",
    "navigation",
    "admin-interface",
}
BACKEND_CAPABILITIES = {
    "route-handlers",
    "server-actions",
    "auth-middleware",
    "trpc-router",
    "data-access",
    "file-storage",
    "email-webhooks",
    "background-jobs",
    "validation-schemas",
    "admin-export",
}
AI_DATA_CAPABILITIES = {
    "llm-harness",
    "local-ai-integration",
    "rag-retrieval",
    "eval-harness",
    "data-pipeline",
    "python-api",
    "python-cli",
    "node-ai-sdk",
    "model-server-integration",
}
PERSONAL_CODE_CAPABILITIES = UI_CAPABILITIES | BACKEND_CAPABILITIES | AI_DATA_CAPABILITIES
DOMAIN_CAPABILITIES = {
    "nextjs-ui": tuple(sorted(UI_CAPABILITIES)),
    "personal-code": tuple(sorted(PERSONAL_CODE_CAPABILITIES)),
}
COMMAND_PALETTE_DEPENDENCIES = {
    "@ariakit/react",
    "@base-ui/react",
    "cmdk",
    "react-aria-components",
}
BACKEND_PATH_PARTS = {
    "actions",
    "api",
    "auth",
    "cron",
    "db",
    "drizzle",
    "inngest",
    "job",
    "jobs",
    "middleware",
    "prisma",
    "queue",
    "route",
    "routes",
    "routers",
    "server",
    "services",
    "sync",
    "worker",
    "workers",
}
BACKEND_CAPABILITY_PATH_TERMS = {
    "route-handlers": {"api", "route", "routes", "router", "routers"},
    "server-actions": {"action", "actions", "server"},
    "auth-middleware": {"auth", "middleware", "session", "sessions", "login"},
    "trpc-router": {"trpc", "router", "routers"},
    "data-access": {"db", "database", "drizzle", "prisma", "schema", "schemas"},
    "file-storage": {
        "attachment",
        "attachments",
        "blob",
        "document",
        "documents",
        "drive",
        "media",
        "r2",
        "s3",
        "storage",
        "upload",
        "uploads",
    },
    "email-webhooks": {"email", "webhook", "webhooks", "message", "handler"},
    "background-jobs": {"cron", "inngest", "job", "jobs", "processor", "queue", "sync", "worker"},
    "validation-schemas": {"schema", "schemas", "validation", "zod", "resolver"},
    "admin-export": {"export", "pdf", "report", "reports", "xlsx", "excel"},
}
AI_DATA_PATH_PARTS = {
    "agents",
    "api",
    "benchmarks",
    "cli",
    "data",
    "datasets",
    "eval",
    "evals",
    "harness",
    "ingest",
    "llm",
    "models",
    "notebooks",
    "pipelines",
    "rag",
    "retrieval",
    "scripts",
    "services",
    "src",
    "tools",
}
AI_DATA_CAPABILITY_PATH_TERMS = {
    "llm-harness": {"agent", "agents", "chat", "completion", "harness", "llm", "prompt"},
    "local-ai-integration": {"llama", "lmstudio", "local", "ollama", "server", "vllm"},
    "rag-retrieval": {"chunk", "embed", "embedding", "index", "rag", "retrieval", "vector"},
    "eval-harness": {"benchmark", "eval", "evals", "grade", "judge", "metric", "test"},
    "data-pipeline": {"data", "duckdb", "etl", "ingest", "pandas", "pipeline", "polars"},
    "python-api": {"api", "fastapi", "router", "routes", "server", "service"},
    "python-cli": {"cli", "command", "main", "typer", "click"},
    "node-ai-sdk": {"ai", "api", "chat", "completion", "generate", "openai", "sdk"},
    "model-server-integration": {"client", "completion", "lmstudio", "model", "ollama", "server"},
}
CAPABILITY_PATH_TERMS = BACKEND_CAPABILITY_PATH_TERMS | AI_DATA_CAPABILITY_PATH_TERMS
BACKGROUND_JOB_STRONG_TERMS = {
    "cron",
    "inngest",
    "job",
    "jobs",
    "processor",
    "queue",
    "sync",
    "worker",
    "workers",
}
BACKGROUND_JOB_FALSE_POSITIVE_TERMS = {
    "service-worker",
    "serviceworker",
    "sw.js",
    "pwa",
}
CAPABILITY_INTENT_HINTS = {
    "data-table": {"data table", "datatable", "tanstack", "table", "columns"},
    "command-palette": {"command palette", "cmdk", "quick navigation", "command"},
    "auth-ui": {"auth", "login", "sign in", "signin", "signup", "password"},
    "settings": {"settings", "profile", "security", "account", "preferences"},
    "dashboard": {"dashboard", "overview", "kpi", "analytics"},
    "forms": {"form", "forms", "multi step", "multi-step", "validation"},
    "file-upload": {"file upload", "upload", "import", "dropzone"},
    "charts": {"chart", "charts", "recharts", "analytics", "graph"},
    "navigation": {"navigation", "sidebar", "navbar", "layout"},
    "admin-interface": {"admin crud", "crud", "detail pages", "admin interface"},
    "route-handlers": {"route handler", "route handlers", "api route", "api routes", "endpoints"},
    "server-actions": {"server action", "server actions", "actions", "admin workflows"},
    "auth-middleware": {"auth middleware", "sessions", "session", "auth helpers", "server-side auth"},
    "trpc-router": {"trpc", "typed api", "router", "routers"},
    "data-access": {"drizzle", "prisma", "data access", "database", "schema"},
    "file-storage": {"file upload", "storage", "drive", "blob", "object storage"},
    "email-webhooks": {"email", "webhook", "webhooks", "message processing", "handlers"},
    "background-jobs": {"background job", "background jobs", "worker", "sync", "scheduled"},
    "validation-schemas": {"validation schema", "validation schemas", "zod", "api inputs"},
    "admin-export": {"admin export", "data export", "reporting", "pdf", "excel", "reports"},
    "llm-harness": {"llm harness", "agent harness", "prompt", "structured output", "tool calling"},
    "local-ai-integration": {"local ai", "lm studio", "lmstudio", "ollama", "llama.cpp", "vllm"},
    "rag-retrieval": {"rag", "retrieval", "embedding", "vector search", "semantic search"},
    "eval-harness": {"eval", "evaluation", "benchmark", "golden", "judge", "metrics"},
    "data-pipeline": {"data pipeline", "duckdb", "polars", "pandas", "etl", "ingest"},
    "python-api": {"fastapi", "python api", "api server", "pydantic", "route"},
    "python-cli": {"python cli", "typer", "click", "command line", "cli"},
    "node-ai-sdk": {"ai sdk", "vercel ai", "openai", "anthropic", "streaming", "chat api"},
    "model-server-integration": {"model server", "openai compatible", "lm studio", "ollama"},
}
