UI_CAPABILITIES = {
    "data-table",
    "command-palette",
    "auth-ui",
    "settings",
    "dashboard",
    "forms",
    "file-upload",
    "charts",
    "navigation",
    "admin-interface",
}
BACKEND_CAPABILITIES = {
    "route-handlers",
    "server-actions",
    "auth-middleware",
    "trpc-router",
    "data-access",
    "file-storage",
    "email-webhooks",
    "background-jobs",
    "validation-schemas",
    "admin-export",
}
AI_DATA_CAPABILITIES = {
    "llm-harness",
    "local-ai-integration",
    "rag-retrieval",
    "eval-harness",
    "data-pipeline",
    "python-api",
    "python-cli",
    "node-ai-sdk",
    "model-server-integration",
}
PERSONAL_CODE_CAPABILITIES = UI_CAPABILITIES | BACKEND_CAPABILITIES | AI_DATA_CAPABILITIES
DOMAIN_CAPABILITIES = {
    "nextjs-ui": tuple(sorted(UI_CAPABILITIES)),
    "personal-code": tuple(sorted(PERSONAL_CODE_CAPABILITIES)),
}
COMMAND_PALETTE_DEPENDENCIES = {
    "@ariakit/react",
    "@base-ui/react",
    "cmdk",
    "react-aria-components",
}
CONCRETE_CAPABILITY_DEPENDENCIES = {
    "data-table": {"@tanstack/react-table"},
    "command-palette": {"cmdk"},
    "auth-ui": {"next-auth"},
    "forms": {"@hookform/resolvers", "react-hook-form", "zod"},
    "file-upload": {"react-dropzone", "uploadthing"},
    "charts": {"recharts"},
    "trpc-router": {"@trpc/server"},
    "data-access": {"@prisma/client", "drizzle-orm", "prisma"},
    "file-storage": {
        "@aws-sdk/client-s3",
        "@vercel/blob",
        "firebase",
        "googleapis",
        "react-dropzone",
        "uploadthing",
    },
    "email-webhooks": {"nodemailer", "resend"},
    "validation-schemas": {"@hookform/resolvers", "zod"},
    "admin-export": {"jspdf", "xlsx"},
    "llm-harness": {
        "@ai-sdk/openai",
        "@ai-sdk/react",
        "ai",
        "anthropic",
        "instructor",
        "litellm",
        "openai",
    },
    "local-ai-integration": {"openai"},
    "rag-retrieval": {
        "@langchain/core",
        "chromadb",
        "langchain",
        "llama-index",
        "qdrant-client",
        "sentence-transformers",
    },
    "eval-harness": {"pytest"},
    "data-pipeline": {"duckdb", "pandas", "polars"},
    "python-api": {"fastapi", "pydantic"},
    "python-cli": {"click", "typer"},
    "node-ai-sdk": {
        "@ai-sdk/anthropic",
        "@ai-sdk/openai",
        "@ai-sdk/react",
        "ai",
        "anthropic",
        "openai",
    },
    "model-server-integration": {"openai"},
}
BACKEND_PATH_PARTS = {
    "actions",
    "api",
    "auth",
    "cron",
    "db",
    "drizzle",
    "inngest",
    "job",
    "jobs",
    "middleware",
    "prisma",
    "queue",
    "route",
    "routes",
    "routers",
    "server",
    "services",
    "sync",
    "worker",
    "workers",
}
BACKEND_CAPABILITY_PATH_TERMS = {
    "route-handlers": {"api", "route", "routes", "router", "routers"},
    "server-actions": {"action", "actions", "server"},
    "auth-middleware": {"auth", "middleware", "session", "sessions", "login"},
    "trpc-router": {"trpc", "router", "routers"},
    "data-access": {"db", "database", "drizzle", "prisma", "schema", "schemas"},
    "file-storage": {
        "attachment",
        "attachments",
        "blob",
        "document",
        "documents",
        "drive",
        "media",
        "r2",
        "s3",
        "storage",
        "upload",
        "uploads",
    },
    "email-webhooks": {"inbound", "mailbox", "nodemailer", "resend", "webhook", "webhooks"},
    "background-jobs": {"cron", "inngest", "job", "jobs", "processor", "queue", "sync", "worker"},
    "validation-schemas": {"schema", "schemas", "validation", "zod", "resolver"},
    "admin-export": {"excel", "export", "exports", "pdf", "xlsx"},
}
AI_DATA_PATH_PARTS = {
    "agents",
    "api",
    "benchmarks",
    "cli",
    "data",
    "datasets",
    "eval",
    "evals",
    "harness",
    "ingest",
    "llm",
    "models",
    "notebooks",
    "pipelines",
    "rag",
    "retrieval",
    "scripts",
    "services",
    "src",
    "tools",
}
AI_DATA_CAPABILITY_PATH_TERMS = {
    "llm-harness": {"agent", "agents", "chat", "completion", "harness", "llm", "prompt", "responses"},
    "local-ai-integration": {"llama", "lmstudio", "local", "ollama", "server", "vllm"},
    "rag-retrieval": {"chunk", "embed", "embedding", "index", "rag", "retrieval", "vector"},
    "eval-harness": {"benchmark", "eval", "evals", "grade", "judge", "metric", "test"},
    "data-pipeline": {"data", "duckdb", "etl", "ingest", "pandas", "pipeline", "polars"},
    "python-api": {"api", "fastapi", "router", "routes", "server", "service"},
    "python-cli": {"cli", "command", "main", "typer", "click"},
    "node-ai-sdk": {"ai", "api", "chat", "completion", "generate", "openai", "sdk"},
    "model-server-integration": {
        "client",
        "completion",
        "lmstudio",
        "model",
        "ollama",
        "responses",
        "server",
    },
}
CAPABILITY_PATH_TERMS = BACKEND_CAPABILITY_PATH_TERMS | AI_DATA_CAPABILITY_PATH_TERMS
BACKGROUND_JOB_STRONG_TERMS = {
    "cron",
    "inngest",
    "job",
    "jobs",
    "processor",
    "queue",
    "sync",
    "worker",
    "workers",
}
BACKGROUND_JOB_FALSE_POSITIVE_TERMS = {
    "service-worker",
    "serviceworker",
    "sw.js",
    "pwa",
}
CAPABILITY_INTENT_HINTS = {
    "data-table": {"data table", "datatable", "tanstack", "table", "columns"},
    "command-palette": {"command palette", "cmdk", "quick navigation", "command"},
    "auth-ui": {"auth", "login", "sign in", "signin", "signup", "password"},
    "settings": {"settings", "profile", "security", "account", "preferences"},
    "dashboard": {"dashboard", "overview", "kpi", "analytics"},
    "forms": {"form", "forms", "multi step", "multi-step", "validation"},
    "file-upload": {"file upload", "upload", "import", "dropzone"},
    "charts": {"chart", "charts", "recharts", "analytics", "graph"},
    "navigation": {"navigation", "sidebar", "navbar", "layout"},
    "admin-interface": {"admin crud", "crud", "detail pages", "admin interface"},
    "route-handlers": {"route handler", "route handlers", "api route", "api routes", "endpoints"},
    "server-actions": {"server action", "server actions", "actions", "admin workflows"},
    "auth-middleware": {"auth middleware", "sessions", "session", "auth helpers", "server-side auth"},
    "trpc-router": {"trpc", "typed api", "router", "routers"},
    "data-access": {"drizzle", "prisma", "data access", "database", "schema"},
    "file-storage": {"file upload", "storage", "drive", "blob", "object storage"},
    "email-webhooks": {"email", "webhook", "webhooks", "message processing", "handlers"},
    "background-jobs": {"background job", "background jobs", "worker", "sync", "scheduled"},
    "validation-schemas": {"validation schema", "validation schemas", "zod", "api inputs"},
    "admin-export": {"admin export", "data export", "reporting", "pdf", "excel", "reports"},
    "llm-harness": {
        "agent harness",
        "llm harness",
        "mocked model",
        "mocked responses",
        "prompt",
        "responses",
        "structured llm",
        "structured output",
        "structured output tests",
        "tool calling",
    },
    "local-ai-integration": {
        "embedding provider",
        "local ai",
        "lm studio",
        "lmstudio",
        "ollama",
        "llama.cpp",
        "vllm",
    },
    "rag-retrieval": {"rag", "retrieval", "embedding", "vector search", "semantic search"},
    "eval-harness": {
        "benchmark",
        "eval",
        "evaluation",
        "golden",
        "golden cases",
        "golden tests",
        "judge",
        "metrics",
        "model responses",
    },
    "data-pipeline": {
        "data pipeline",
        "duckdb",
        "etl",
        "ingest",
        "local analytics",
        "pandas",
        "polars",
        "preprocessing",
    },
    "python-api": {"backend", "fastapi", "python api", "api server", "pydantic", "route"},
    "python-cli": {"python cli", "typer", "click", "command line", "cli"},
    "node-ai-sdk": {
        "@ai-sdk/openai",
        "ai route",
        "ai sdk",
        "anthropic",
        "responses api",
        "openai",
        "streaming",
        "streaming chat",
        "vercel ai",
    },
    "model-server-integration": {
        "ai service",
        "base_url",
        "model client",
        "model server",
        "openai compatible",
        "openai-compatible",
        "lm studio",
        "ollama",
        "responses",
    },
}
